### ISSUE TITLE
flashing problem

### ISSUE THREAD

**Issue by john-clark** [mcheah/Marlin4MPMD#9]
**Describe the bug**
Flashing is problematic if it even works.

**To Reproduce**
1. power off printer
2. format factory sd card
 a. diskpart
 b. select disk 1
 c. clean
 d. create par pri
 e. format fs=fat32 unit=512 quick
3. download firmware_5ALimit_v43+.bin and fcupdate.flg from:  https://github.com/mcheah/Marlin4MPMD/releases/tag/1.2.2
4. rename firmware_5ALimit_v43+.bin to firmware.bin
5. copy both firmware.bin and fcupdate.flg to sdcard
6. right click eject sdcard
7. put sdcard in printer
8. power on printer
9. printer does not display version
10. after 4 seconds printer flashes white light for about 3 seconds
11. the display then changes to the print display
12. power down printer, eject sdcard
13. printer does not display version number
14. when printer is booted V99.160.3 is displayed on top of the preheat area. moving the selection bar covers up half the numbers

**Expected behavior**
Step 7 says firmware version should be displayed after flash this does not happen
https://www.mpminidelta.com/firmware/motion_controller

I expected to also see v44 version number not v99 and prior to image for selecting the printer fuctions not on top.

I have no idea if this is correct since I have no points of reference for the version numbers.

**Comment by john-clark** [comment]
Flashing back to the stock firmware following the above procedure actually did not display that it was printing when the flash was done, it displayed the firmware number. I powered down and the function was back to normal, displaying the version below the IIIp before the selection screen, instead of on top of it. Closing issue.

**Comment by mcheah** [comment]
You are flashing custom firmware on your printer that replaces the stock firmware of your printer.  My boot procedure is slightly different than the stock firmware so the version number is displayed 1-2 seconds after boot.  I use v99 to indicate clearly that the stock firmware is not loaded on the printer.  If you see this then you have successfully upgraded to Marlin4MPMD.  
I've had a couple people report that  they have issues with the v99 version number being stuck on the screen and the printer freezing.  I think this may be caused by different versions of the LCD UI firmware.  I don't have these versions to test so it's difficult for me to reproduce, but you can try sending `M117 {SYS:STARTED}` to the printer over USB, which should reset it to the home screen.  If this is a persistent issue, you can add the command above to M_CFG.G stored on the SD card and it will get executed on boot.
If you flash back to the original firmware, the version number should return to the normal point in boot.
Let me know if you have further issues.

**Comment by john-clark** [comment]
I was just thrown off by the printing screen after the flash vs the version number display. 

I don't think this is even an issue and therefore closed it.

**Comment by mcheah** [comment]
No problem.  Happy to help.
